### ISSUE TITLE
org.eclipse.jetty.client.HttpResponseException

### ISSUE THREAD

**Issue by Charlweed** [Juraji/Pinterest-Downloader#3]
I supplied my access token and tied to download from my boards, but I got nothing but exceptions when I pressed  "Start".

```
java.util.concurrent.ExecutionException: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header
        at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118)
        at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101)
        at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:652)
        at nl.juraji.pinterestdownloader.io.ApiHandler.doRequest(ApiHandler.java:105)
        at nl.juraji.pinterestdownloader.io.ApiHandler.doGet(ApiHandler.java:92)
        at nl.juraji.pinterestdownloader.io.ApiHandler.fetchPaged(ApiHandler.java:76)
        at nl.juraji.pinterestdownloader.io.ApiHandler.getMyBoards(ApiHandler.java:61)
        at nl.juraji.pinterestdownloader.ui.workers.ProcessWorker.downloadBoards(ProcessWorker.java:66)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header
        at org.eclipse.jetty.client.AuthenticationProtocolHandler$AuthenticationListener.onComplete(AuthenticationProtocolHandler.java:114)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:459)
        at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:405)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:281)
        at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1518)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1335)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:170)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:131)
        at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:70)
        at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:130)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:116)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:261)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:150)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:112)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
        at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)

```

**Comment by Juraji** [comment]
Hey @Charlweed & @lachlan-roberts, sorry for the late response!
I'm going to archive this project, since it doesn't work with Pinterest anymore.

If you loved this, I created a new, more advanced app: https://github.com/Juraji/image-manager-2
It supports the current Pinterest layout (Since I used it just yesterdayy to sync up my backup :D)
